const clientsKey = 'gamayun-clients';
const sessionKey = 'gamayun-current-client';
const accountTabs = document.querySelectorAll('[data-account-tab]');
const loginAccount = document.querySelector('#login-account');
const registerAccount = document.querySelector('#register-account');
const accountNote = document.querySelector('#account-note');
const authCard = document.querySelector('#auth-card');
const dashboard = document.querySelector('#account-dashboard');

function readClients() { try { return JSON.parse(localStorage.getItem(clientsKey)) || []; } catch { return []; } }
function showDashboard(client) { authCard.hidden = true; dashboard.hidden = false; document.querySelector('#dashboard-name').textContent = client.name; document.querySelector('#dashboard-email').textContent = client.email; let bookings = []; try { bookings = JSON.parse(localStorage.getItem('gamayun-bookings')) || []; } catch { bookings = []; } const mine = bookings.filter((booking) => booking.email === client.email); document.querySelector('#my-bookings').innerHTML = mine.length ? mine.map((booking) => `<article class="account-booking"><strong>${booking.service}</strong><span>${new Intl.DateTimeFormat('ru-RU', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(booking.date))}, ${String(booking.hour).padStart(2, '0')}:00</span><small>${booking.status}</small></article>`).join('') : '<div class="booking-empty"><strong>Бронирований пока нет</strong><p>Выберите формат и удобное время — встреча появится здесь.</p></div>'; }
function currentClient() { try { return JSON.parse(localStorage.getItem(sessionKey)); } catch { return null; } }

accountTabs.forEach((tab) => tab.addEventListener('click', () => { const isLogin = tab.dataset.accountTab === 'login'; accountTabs.forEach((item) => item.classList.toggle('is-active', item === tab)); loginAccount.hidden = !isLogin; registerAccount.hidden = isLogin; accountNote.textContent = isLogin ? 'Введите e-mail и пароль, указанные при регистрации.' : 'После регистрации можно войти в личный кабинет.'; }));
registerAccount.addEventListener('submit', (event) => { event.preventDefault(); const name = registerAccount.querySelector('input[type="text"]').value.trim(); const email = registerAccount.querySelector('input[type="email"]').value.trim().toLowerCase(); const password = registerAccount.querySelector('input[type="password"]').value; const clients = readClients(); const existing = clients.findIndex((client) => client.email === email); const client = { id: existing >= 0 ? clients[existing].id : `client-${Date.now()}`, name, email, password, registeredAt: existing >= 0 ? clients[existing].registeredAt : new Date().toISOString(), emailConfirmed: existing >= 0 ? clients[existing].emailConfirmed : false }; if (existing >= 0) clients[existing] = client; else clients.unshift(client); localStorage.setItem(clientsKey, JSON.stringify(clients)); localStorage.setItem(sessionKey, JSON.stringify(client)); showDashboard(client); });
loginAccount.addEventListener('submit', (event) => { event.preventDefault(); const email = loginAccount.querySelector('input[type="email"]').value.trim().toLowerCase(); const password = loginAccount.querySelector('input[type="password"]').value; const clients = readClients(); const index = clients.findIndex((item) => item.email === email); if (index < 0) { accountNote.textContent = 'Такого e-mail пока нет в демо-базе. Сначала зарегистрируйтесь.'; return; } const client = clients[index]; if (!client.password) { client.password = password; clients[index] = client; localStorage.setItem(clientsKey, JSON.stringify(clients)); } if (client.password !== password) { accountNote.textContent = 'Проверьте пароль.'; return; } localStorage.setItem(sessionKey, JSON.stringify(client)); showDashboard(client); });
document.querySelector('#account-logout').addEventListener('click', () => { localStorage.removeItem(sessionKey); dashboard.hidden = true; authCard.hidden = false; loginAccount.reset(); });
document.querySelectorAll('[data-social]').forEach((button) => button.addEventListener('click', () => { accountNote.textContent = `Вход через ${button.dataset.social} подключим после настройки настоящей авторизации.`; }));
const savedClient = currentClient(); if (savedClient) showDashboard(savedClient);
